name: Build Debian Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Debian package building environment
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev

    - name: Build Debian package
      run: |
        cd ../
        dpkg-deb --build delete-old-downloads
        mv delete-old-downloads.deb delete-old-downloads/

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: delete-old-downloads.deb
        path: delete-old-downloads.deb

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: delete-old-downloads.deb
        asset_name: delete-old-downloads.deb
        tag: v1.0.0
        overwrite: true
        body: "This is my release text"
